import LibraryMenu from "@/components/LibraryMenu";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900">

  {/* Global Navigation */}
  <nav className="fixed top-0 left-0 w-full bg-white border-b border-zinc-200 z-50">
    <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
      <div className="tracking-wide text-sm">
        SENSORY ARCHIVE
      </div>

      <div className="flex gap-8 text-sm tracking-widest">
        <a href="/">HOME</a>
     <LibraryMenu />
        <a href="/post">POST</a>
        <a href="/media">MEDIA</a>
        <a href="/contact">CONTACT</a>
      </div>
    </div>
  </nav>

  {/* page content */}
  <main className="pt-24">
    {children}
  </main>

</body>
    </html>
  );
}
